<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KOMAL" failures="1" tests="2" name="TestCases.DemoTest" time="8.386" errors="0" timestamp="2023-01-05T13:33:19 IST" skipped="1">
  <testcase classname="TestCases.DemoTest" name="verifyTitleTest1" time="8.386">
    <failure message="Test case fail jhali ka expected [Swag Labs] but found [1Swag Labs]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test case fail jhali ka expected [Swag Labs] but found [1Swag Labs]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at TestCases.DemoTest.verifyTitleTest1(DemoTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- verifyTitleTest1 -->
  <testcase classname="TestCases.DemoTest" name="verifyTitleTest">
    <skipped/>
  </testcase> <!-- verifyTitleTest -->
</testsuite> <!-- TestCases.DemoTest -->
